name: Godot Web Export
on: push

env:
  GODOT_VERSION: 3.5.3
  EXPORT_NAME: ludum-dare-56

jobs:
  export-web:
    name: Web Export
    runs-on: ubuntu-24.04
    container:
      image: davesilva/godot-ci:3.5.3
    steps:
      - name: Checkout
        uses: actions/checkout@v1
        with:
          lfs: true
      - name: Setup
        run: |
          mkdir -v -p ~/.local/share/godot/templates/
          mv /root/.local/share/godot/templates/${GODOT_VERSION}.stable ~/.local/share/godot/templates/${GODOT_VERSION}.stable
      - name: Web Build
        run: |
          mkdir -v -p build
          godot --no-window --verbose --export "HTML5" build/index.html
      - name: Edit JS to remove checks for serviceWorker
        run: |
          cd build
          sed -i "s/[\"']serviceWorker[\"'] *in *navigator/false/g" index.js
      - name: Create ZIP
        run: |
          cd build
          zip ../build.zip *
      - name: Upload Artifact
        uses: actions/upload-artifact@v4
        with:
          name: web
          path: build.zip
    
  build-server-docker-image:
    name: Build Server Docker Image
    runs-on: ubuntu-24.04
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          lfs: true
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3
      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      - name: Build and push
        uses: docker/build-push-action@v6
        with:
          push: true
          tags: davesilva/ludum-dare-56:${{ github.sha }}
          cache-from: type=registry,ref=davesilva/ludum-dare-56:${{ github.event.before }}
          cache-to: type=inline


  release:
    name: Release
    needs: export-web
    runs-on: ubuntu-24.04
    if: startsWith(github.ref, 'refs/tags/')
    permissions:
      contents: write
    steps:
      - name: Download Artifact
        uses: actions/download-artifact@v4
        with:
          name: web
      - name: Release
        uses: softprops/action-gh-release@v2
        with:
          files: build.zip

